name: test
on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_EXPERIMENTAL: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
          save-if: ${{ github.ref_name == 'main' }}
      - uses: taiki-e/install-action@cargo-binstall
      - uses: jdx/mise-action@v2
      - run: mise r build
      - run: mise r test
      - run: mise r lint
